# Generated by Django 4.2.23 on 2025-07-22 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genericos', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='rubro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genericos.rubro'),
        ),
    ]
